{
  "formatVersion": "1.1",
  "component": {
    "group": "com.themediatrust",
    "module": "media-filter-sdk",
    "version": "1.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "media-filter-sdk-1.2.4.aar",
          "url": "media-filter-sdk-1.2.4.aar",
          "size": 176826,
          "sha512": "cad268a1cb9e84a1c1e80a97e7d90ecb3b98dffe57c3c82e21f2dd54c4137f43ebf3d30512e47980bd68d8e882a3b83784b7350e506aa74506d3cc03d09ce00a",
          "sha256": "58c98fb07f1e9864a5245981c4bf072d1c6553774a4a18e2561bd3535e8eaad7",
          "sha1": "118c78c255656dc5077c24923a1c86e84d3c6cff",
          "md5": "e20caefecee8f00ef5d93ffc317a26fd"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "media-filter-sdk-1.2.4.aar",
          "url": "media-filter-sdk-1.2.4.aar",
          "size": 176826,
          "sha512": "cad268a1cb9e84a1c1e80a97e7d90ecb3b98dffe57c3c82e21f2dd54c4137f43ebf3d30512e47980bd68d8e882a3b83784b7350e506aa74506d3cc03d09ce00a",
          "sha256": "58c98fb07f1e9864a5245981c4bf072d1c6553774a4a18e2561bd3535e8eaad7",
          "sha1": "118c78c255656dc5077c24923a1c86e84d3c6cff",
          "md5": "e20caefecee8f00ef5d93ffc317a26fd"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "media-filter-sdk-1.2.4-sources.jar",
          "url": "media-filter-sdk-1.2.4-sources.jar",
          "size": 220310,
          "sha512": "a4b2911929fd69054483cab04ac62b926072805d4e2e97dce513e28d06e9f4eb2154a547e1c65b081a1ff0ef9877bd3b7d36d64d449d18b21e6980f7f72dca30",
          "sha256": "7bc45051aeb5e1e30bcb137f4aabfd4b4075f0799c53e38d7f03ca3eda665fb8",
          "sha1": "d9f7abb9b241af6be703539309d476d9bfa0d72d",
          "md5": "31fe1faf840e765bca7a6a6223244c6b"
        }
      ]
    }
  ]
}
