{
  "formatVersion": "1.1",
  "component": {
    "group": "com.themediatrust",
    "module": "media-filter-sdk",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "media-filter-sdk-1.2.3.aar",
          "url": "media-filter-sdk-1.2.3.aar",
          "size": 180446,
          "sha512": "e6bf35660afe95ae63f9f461ce1727f4ef12082d9b9ed08da332d37e345e77038ec9f948f91adfd937f7bbc6e5b60017c02c7c46d7c1b2204b2c0a1720d4b1cf",
          "sha256": "0cf31037e86c6e0e41f06505cf4804dee3a57f10a44d2cb24f78c7c0f9444773",
          "sha1": "7778ef49b5402dd1f9d464c3e4a765f5a5765359",
          "md5": "ecb6cc3462a5e0d42318bcf0d737f95e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "media-filter-sdk-1.2.3.aar",
          "url": "media-filter-sdk-1.2.3.aar",
          "size": 180446,
          "sha512": "e6bf35660afe95ae63f9f461ce1727f4ef12082d9b9ed08da332d37e345e77038ec9f948f91adfd937f7bbc6e5b60017c02c7c46d7c1b2204b2c0a1720d4b1cf",
          "sha256": "0cf31037e86c6e0e41f06505cf4804dee3a57f10a44d2cb24f78c7c0f9444773",
          "sha1": "7778ef49b5402dd1f9d464c3e4a765f5a5765359",
          "md5": "ecb6cc3462a5e0d42318bcf0d737f95e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "media-filter-sdk-1.2.3-sources.jar",
          "url": "media-filter-sdk-1.2.3-sources.jar",
          "size": 226829,
          "sha512": "228bfa7e57066515c2cd2ed1a155acb9f25b7226ed4640b0afdce4d061b36faa76e4de993bbeaed2cf4aead7ddefb2ba2ff6a1fb9a54319f5ca7fe682916a8a3",
          "sha256": "9cb09acf9402ec1ef858e5251284dda567d7c4c6da43a920d1f026f8769ab319",
          "sha1": "b801b32c973c76c8098c5bf0c6c58ed3ca66d535",
          "md5": "0994df6e29a5ee4aec601449088f997d"
        }
      ]
    }
  ]
}
